require_relative '../book'
require_relative '../person'
require_relative '../rental'
require_relative '../nameable'
require_relative '../basedecorator'
require_relative '../capitalizedecorator'
require_relative '../classroom'
require_relative '../mybooks'
require_relative '../mypersons'
require_relative '../myrentals'
require_relative '../student'
require_relative '../teacher'
require_relative '../trimmerdecorator'

require 'yaml'
